CREATE TABLE public.fake (
    numero integer NOT NULL,
    genero character varying(6) NOT NULL,
    nameset character varying(25) NOT NULL,
    tratamento character varying(6) NOT NULL,
    primeiro_nome character varying(20) NOT NULL,
    inicial_nome_meio character varying(1) NOT NULL,
    sobrenome character varying(23) NOT NULL,
    endereco character varying(100) NOT NULL,
    cidade character varying(100) NOT NULL,
    estado character varying(22) NOT NULL,
    estado_completo character varying(100) NOT NULL,
    codigo_postal character varying(15) NOT NULL,
    pais character varying(2) NOT NULL,
    pais_completo character varying(100) NOT NULL,
    endereco_de_email character varying(100) NOT NULL,
    nome_de_usuario character varying(25) NOT NULL,
    senha character varying(25) NOT NULL,
    agente_usuario_navegador character varying(255) NOT NULL,
    numero_telefone character varying(25) NOT NULL,
    codigo_pais_telefone integer NOT NULL,
    maiden_name character varying(20) NOT NULL,
    data_nascimento character varying(10) NOT NULL,
    idade integer NOT NULL,
    signo_tropical character varying(11) NOT NULL,
    tipo_cartao character varying(10) NOT NULL,
    numero_cartao character varying(16) NOT NULL,
    cvv2 character varying(3) NOT NULL,
    validade_cartao character varying(10) NOT NULL,
    cpf character varying(20) NOT NULL,
    codigo_rastreamento_upstracking character varying(24) NOT NULL,
    numero_mtc_western_union character(10) NOT NULL,
    numero_mtc_moneygram character(8) NOT NULL,
    cor character varying(6) NOT NULL,
    profissao character varying(70) NOT NULL,
    empresa character varying(70) NOT NULL,
    veiculo character varying(255) NOT NULL,
    dominio character varying(70) NOT NULL,
    tipo_sanguineo character varying(3) NOT NULL,
    peso_libras character varying(5) NOT NULL,
    peso_quilos character varying(5) NOT NULL,
    altura_polegadas character varying(6) NOT NULL,
    altura_centimetros character varying(3) NOT NULL,
    identificador_global character varying(36) NOT NULL,
    latitude numeric(10,6) NOT NULL,
    longitude numeric(10,6) NOT NULL
);


COPY fake FROM
  '/tmp/fakenames.csv' csv header delimiter ';' quote '"';
  
